### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by pjmpessers** [MaxvandeLaar/homey-webos-plus#24]
The app crashes when installing my oled cx on homey fw5.0rc26.

Sideload v2.2.1 and install oledtv in devices.

**Comment by pjmpessers** [comment]
Installed v2.2.0 and this one works great. Only v2.2.1 crashes. 

Happy with v2.2.0

**Comment by twister5800** [comment]
Hi,

Also have this issue, only 2.2.0 works, 2.2.1 crashes instantly when TV with WebOS 3.12 is configured.

other than that, thanks for a great app ;-)

best regards
Martin

**Comment by MaxvandeLaar** [comment]
@pjmpessers sorry for the late response, I have been working really hard on [https://store.homey.community]() and I am going to shift my focus backt to WebOS a little more.

@twister5800 @pjmpessers 

If one of you could try to run the app by downloading it from this GitHub, unzip it, and run the following commands in your terminal.

`npm install`

followed by

`homey app run`

This will display all the debug logging. If you could upload (copy/paste) the logging, including the error and logging before that, here that would be really helpful. Please check for any sensitive information before you upload of course.

**Comment by pjmpessers** [comment]
Hello Max. 

Good to hear your on it again. It wasn.t a problem. Here you have my logging. I hope it helps. 


2021-02-04 22:42:59 [log] [WebosPlus] WebOS Plus is running...
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'node-fetch'
Require stack:
- /drivers/webos_plus/device.js
- /opt/homey-client/node_modules/homey-apps-sdk-v2/lib/Driver.js
- /opt/homey-client/node_modules/homey-apps-sdk-v2/index.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.require (/opt/homey-client/node_modules/homey-apps-sdk-v2/index.js:14:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/drivers/webos_plus/device.js:22:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/drivers/webos_plus/device.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v2/lib/Driver.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v2/index.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap.js'
  ]
}

--- INFO: com.maxvandelaar.webos-plus has been killed ---

**Comment by MaxvandeLaar** [comment]
Thanks @pjmpessers How did you install the app before? Did you downloaded it from Github and ran the CLI command or did you use the [https://store.homey.community]()? 

I have seen this issue a few times when downloaded from Github, for some reason `node-fetch` doesn't always get installed from `npm` correctly.

**Comment by pjmpessers** [comment]
I think i did it with homey store.  But it was a long time ago. Somehow i don't see it in the store. So i sideloaded it.

**Comment by MaxvandeLaar** [comment]
It should be there ;) in the Video section [https://store.homey.community/category/video]() [https://store.homey.community/app/com.maxvandelaar.webos-plus]()

So if you sideboard the app, try to run `npm install` before running `homey app install`. This will most likely fix the issue. But I'd like to ask you to first try to install the HCS version (its the same) so I can tell if there is any underlying issue I am not seeing.

**Comment by pjmpessers** [comment]
I don't see it anymore. Only the LG WebOS from homey themself. Maybe because i use FW 5.0.0 rc62?

**Comment by MaxvandeLaar** [comment]
Did you clicked the links I put above? that is my app of course ;). The WebOS plus app was never in de official store, only in my Homey Community Store. 

Note, I forgot to add the correct hyperlink before, so try clicking them again sorry ;)

**Comment by pjmpessers** [comment]
Now i see it. But the button install is grayed out.

**Comment by pjmpessers** [comment]
Hello Max. 

Great news. I couldn't install thru the https://store.homey.community/app/com.maxvandelaar.webos-plus. I think i do something wrong. But you are right. I sideloaded it, but before that i did: 'npm install'. And that helped.
Thanks for your help. I want to give you a small donation, but i dislike paypall.  Can i do it with a banktransfer?

**Comment by MaxvandeLaar** [comment]
This most likely means you don't have the required setup yet to download and install apps.  [https://store.homey.community/hcs](https://store.homey.community/hcs) and don't forget to sign in by going to the green navigation bubble center item ;)
