### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by sossienl** [MaxvandeLaar/homey-webos-plus#4]
**Describe the bug**
App after install from Git worked ok. Added device (went ok), now it constantly crashes.
Setup: LG OLED 55C7V running 05.80.35

**To Reproduce**
Not sure. Restart the app, but it crashes again

Please do let me know if I need to share antything else

**Comment by MaxvandeLaar** [comment]
@sossienl Sorry to hear you are experiencing these crashes. If possible, could you install the app by running `homey app run` instead of the `install` command. This way the log will show in your terminal which will probably give a hint to what is happening. Can you please share what the error log shows?

**Comment by sossienl** [comment]
2020-02-19 15:13:06 [log] [WebosPlus] WebOS Plus is running...
module.js:550
    throw err;
    ^

Error: Cannot find module 'node-wol'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/drivers/webos_plus/device.js:4:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

--- INFO: com.maxvandelaar.webos-plus has been killed ---

**Comment by MaxvandeLaar** [comment]
Thanks for the fast reply. This is luckily an easy fix. It appears the npm package 'node-wol' did not correctly install.

Did you downloaded the source code or the webos-plus.zip file?

In any case, try to run `npm install` in the project folder and check if node-wol exists in the 'node_modules' folder. Then try to install the app again.

**Comment by sossienl** [comment]
Worked! Thanks!

**Comment by MaxvandeLaar** [comment]
Good to hear! Good luck with it 😉!
